-- AMPS Client Code snippets
local snippets = {
  amps_config = {
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<AMPSConfig>",
    "",
    "  <Name>snippet</Name>",
    "",
    "  <Admin>",
    "    <InetAddr>localhost:8085</InetAddr>",
    "    <FileName>./admin/stats.db</FileName>",
    "    <Interval>1s</Interval>",
    "    <SQLTransport>websocket-any</SQLTransport>",
    "  </Admin>",
    "",
    "  <Transports>",
    "    <Transport>",
    "      <Name>any-tcp</Name>",
    "      <Type>tcp</Type>",
    "      <InetAddr>9007</InetAddr>",
    "      <Protocol>amps</Protocol>",
    "    </Transport>",
    "",
    "    <!-- galvanometer -->",
    "    <Transport>",
    "      <Name>websocket-any</Name>",
    "      <Protocol>websocket</Protocol>",
    "      <Type>tcp</Type>",
    "      <InetAddr>9008</InetAddr>",
    "    </Transport>",
    "  </Transports>",
    "",
    "  <TransactionLog>",
    "    <JournalDirectory>./journal</JournalDirectory>",
    "    <MinJournalSize>100MB</MinJournalSize>",
    "    <Topic>",
    "      <Name>.*</Name>",
    "      <MessageType>json</MessageType>",
    "    </Topic>",
    "  </TransactionLog>",
    "",
    "  <Logging>",
    "    <Target>",
    "      <Protocol>file</Protocol>",
    "      <FileName>./logs/amps.log</FileName>",
    "      <Level>developer</Level>",
    "      <IncludeErrors>00-0000</IncludeErrors>",
    "    </Target>",
    "  </Logging>",
    "",
    "  <SOW>",
    "    <Topic>",
    "      <Name>sow_topic</Name>",
    "      <MessageType>json</MessageType>",
    "      <FileName>./sow/%n.sow</FileName>",
    "      <Key>/id</Key>",
    "    </Topic>",
    "",
    "    <Topic>",
    "      <Name>action_topic</Name>",
    "      <MessageType>json</MessageType>",
    "      <FileName>./sow/%n.sow</FileName>",
    "      <Key>/id</Key>",
    "    </Topic>",
    "",
    "    <View>",
    "      <Name>example_view</Name>",
    "      <UnderlyingTopic>",
    "        <Join>[sow_topic]./id = [action_topic]./id</Join>",
    "      </UnderlyingTopic>",
    "      <MessageType>json</MessageType>",
    "      <Projection>",
    "        <Field>[sow_topic]./id as /sow_topic_id</Field>",
    "        <Field>[action_topic]./id as /action_topic_id</Field>",
    "      </Projection>",
    "      <Grouping>",
    "        <Field>[sow_topic]./id</Field>",
    "      </Grouping>",
    "    </View>",
    "",
    "    <Queue>",
    "      <Name>example_queue</Name>",
    "      <UnderlyingTopic>sow_topic</UnderlyingTopic>",
    "      <MessageType>json</MessageType>",
    "      <Semantics>at-least-once</Semantics>",
    "    </Queue>",
    "  </SOW>",
    "",
    "  <Actions>",
    "    <Action>",
    "      <On>",
    "        <Module>amps-action-on-publish-message</Module>",
    "        <Options>",
    "          <Topic>sow_topic</Topic>",
    "          <MessageType>json</MessageType>",
    "        </Options>",
    "      </On>",
    "      <Do>",
    "        <Module>amps-action-do-publish-message</Module>",
    "        <Options>",
    "          <Topic>action_topic</Topic>",
    "          <MessageType>json</MessageType>",
    "          <Data>{{AMPS_DATA}}</Data>",
    "        </Options>",
    "      </Do>",
    "    </Action>",
    "  </Actions>",
    "</AMPSConfig>"
  },
  cpp = {
    "// C++",
    "#include <amps/ampsplusplus.hpp>",
    "#include <iostream>",
    "",
    "// Compile / Run:",
    "// g++ -I ~/ampsClients/amps-c++-client-5.3.5.0-Linux/include/ Example.cpp ~/ampsClients/amps-c++-client-5.3.5.0-Linux/lib/x86_64/debug/libamps.a -o Example",
    "// (LD_LIBRARY_PATH=~/gfs/oss/gcclib/12.2.0 may need to be prepended to ^ sometimes))",
    "// ./Example",
    "",
    "int main()",
    "{",
    "  const char* uri = \"tcp://localhost:9007/amps/json\";",
    "  const char* topic = \"sow_topic\";",
    "",
    "  AMPS::Client client(\"ExampleClient\");",
    "",
    "  try",
    "  {",
    "    client.connect(uri);",
    "    client.logon();",
    "",
    "    AMPS::Command cmd(\"sow\");",
    "    cmd.setTopic(topic);",
    "",
    "    for (auto msg : client.execute(cmd))",
    "    {",
    "      if (msg.getCommand() == \"sow\")",
    "      {",
    "        std::cout << msg.getData() << std::endl;",
    "      }",
    "    }",
    "  } catch (AMPS::AMPSException& e) {",
    "    std::cerr << e.what() << std::endl;",
    "    return -1;",
    "  }",
    "  return 0;",
    "}"
  },
  csharp = {
    "// CSharp",
    "using System;",
    "using AMPS.Client;",
    "using AMPS.Client.Exceptions;",
    "",
    "// Compile / Run:",
    "// csc /unsafe Example.cs ~/ampsClients/amps-csharp-client-5.3.5.0/AMPS.Client/**/*.cs",
    "// dotnet ./Example.exe",
    "",
    "Client amps = new Client(\"myapplication\");",
    "",
    "try",
    "{",
    "    amps.connect(\"tcp://192.168.0.2:9007/amps/json\");",
    "    amps.logon();",
    "",
    "    foreach (Message msg in amps.subscribe(\"orders\", \"/symbol LIKE 'ABCD'\"))",
    "    {",
    "          Console.WriteLine(msg.Data);",
    "    }",
    "}",
    "catch (AMPSException exception)",
    "{",
    "    Console.WriteLine(exception);",
    "}",
  },
  java = {
    "// Java",
    "import com.crankuptheamps.client.Client;",
    "import com.crankuptheamps.client.Command;",
    "import com.crankuptheamps.client.MessageHandler;",
    "import com.crankuptheamps.client.Message;",
    "import com.crankuptheamps.client.exception.AMPSException;",
    "import java.io.IOException;",
    "",
    "// Compile / Run:",
    "// javac -classpath ~/ampsClients/amps-java-client-5.3.5.0/dist/lib/amps_client.jar Example.java",
    "// java -cp \".:/home/rparker/ampsClients/amps-java-client-5.3.5.0/dist/lib/amps_client.jar\" Example",
    "",
    "public class Example",
    "{",
    "    public static void main(String[] args) {",
    "        Client client = new Client(\"TestPublisher-Client\");",
    "        try {",
    "            client.connect(\"tcp://localhost:9007/amps/json\");",
    "            client.logon();",
    "",
    "            Command cmd = new Command(\"subscribe\").setTopic(\"sow_topic\").setSubId(\"custom-sub-id\");",
    "",
    "            client.executeAsync(cmd, new MessageHandler() {",
    "                @Override",
    "                public void invoke(Message message) {",
    "                    System.out.println(\"Received: \" + message.getData());",
    "                }",
    "            });",
    "",
    "            System.out.println(\"Subscribed. Press ENTER to quit.\");",
    "            System.in.read();  // blocks until user presses Enter",
    "        }",
    "        catch (AMPSException | IOException aex) {",
    "            System.err.println(\"TestListener caught exception.\");",
    "        } finally {",
    "            client.close();",
    "        }",
    "    }",
    "}",
  },
  js = {
    "const amps = require('/home/rparker/ampsClients/amps-javascript-client-5.3.4.0/amps')",
    "// const { Client, Command } = import('./lib/amps')  # import only Client + Command",
    "",
    "// Compile / Run:",
    "// node Example.js",
    "",
    "function sleep(ms) {",
    "  console.log(\"Sleeping\")",
    "  return new Promise(resolve => setTimeout(resolve, ms))",
    "}",
    "",
    "const uri = \"ws://localhost:9008/amps/json\"",
    "",
    "async function main() {",
    "  const client = new amps.Client(\"examplePublisher\")",
    "",
    "  try {",
    "    await client.connect(uri)",
    "",
    "    cmd = new amps.Command(\"subscribe\").topic(\"sow_topic\").subId(\"custom-sub-id\")",
    "    await client.execute(cmd, m => {",
    "      console.log(m.data)",
    "    })",
    "",
    "    await sleep(2000) // sleep 2 seconds",
    "",
    "    client.disconnect()",
    "  } catch (err) {",
    "    console.error(err)",
    "  }",
    "}",
    "",
    "main()",
  },
  python = {
    "# Python",
    "from AMPS import *",
    "",
    "client = Client(\"my-application\")",
    "uri = 'tcp://localhost:9007/amps/json'",
    "topic = 'sow_topic'",
    "",
    "try:",
    "    client.connect(uri)",
    "    client.logon()",
    "",
    "    cmd = Command('sow').set_topic(topic)",
    "",
    "    for m in client.execute(cmd):",
    "        if m.get_command() == 'sow':",
    "            print(m.get_data())",
    "",
    "except Exception as e:",
    "    print(e)"
  },
  taskset = {
    "start_cmd = 'taskset --cpu-list %s,%s %s' % (cpu_0_list, cpu_1_list, server_loc)",
    "with Instance(start_cmd, os.path.join(testdir, 'config.xml')) as server:",
  }
}

return snippets
